apiVersion: 1

datasources:
  - name: Local-Tempo
    uid: local-tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: true

    jsonData:
      httpMethod: GET

      nodeGraph:
        enabled: true

      tracesToLogsV2:
        datasourceUid: local-loki
        spanStartTimeShift: -5m
        spanEndTimeShift: 5m
        filterByTraceID: true
        filterBySpanID: true